const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand()}
const SUPABASE_URL="https://mshoftgubfbkvynndtnu.supabase.co";
const SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zaG9mdGd1YmZia3Z5bm5kdG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY2NDkwOTQsImV4cCI6MjEwMjIyNTA5NH0.vcebPtNubpl8s34D-YsZ6jQwH93-MA0wgyDZBiO0Hi4";
const API=`${SUPABASE_URL}/rest/v1/posts`, REQUIRED=3;let videos=[],selected=null,ads=0,loading=false,category="All";
const grid=document.getElementById("videoGrid"),status=document.getElementById("status"),modal=document.getElementById("modal"),title=document.getElementById("modalTitle"),text=document.getElementById("modalText"),preview=document.getElementById("previewImage"),adBtn=document.getElementById("watchAdBtn"),videoBtn=document.getElementById("videoBtn"),bar=document.getElementById("progressBar");
if(tg?.initDataUnsafe?.user)document.getElementById("tgUser").textContent=`👤 ${tg.initDataUnsafe.user.first_name||"Telegram User"}`;
async function load(){try{const r=await fetch(`${API}?select=id,title,text,thumbnail_url,video_url,category,published&published=eq.true&order=id.desc`,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`}});if(!r.ok)throw Error(await r.text());videos=await r.json();status.classList.add("hidden");render()}catch(e){console.error(e);status.textContent="Supabase থেকে ভিডিও লোড হচ্ছে না। posts table-এর SELECT/RLS policy চেক করুন।";grid.innerHTML='<div class="empty">⚠️ কোনো পোস্ট পাওয়া যায়নি</div>'}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){grid.innerHTML="";const list=category==="All"?videos:videos.filter(v=>(v.category||"").toLowerCase()===category.toLowerCase());if(!list.length){grid.innerHTML='<div class="empty">🎬 এই ক্যাটাগরিতে কোনো ভিডিও নেই।</div>';return}list.forEach((v,i)=>{const c=document.createElement("article");c.className="card";c.innerHTML=`<div class="thumb-wrap">${v.thumbnail_url?`<img class="thumb" src="${esc(v.thumbnail_url)}" onerror="this.style.display='none'">`:''}<span class="rank">#${i+1}</span></div><div class="body"><h3 class="title">${esc(v.title||"Untitled Video")}</h3><div class="cat">${esc(v.category||"Popular")} · 3 ads</div><button class="ad">Watch Ads (0/3)</button></div>`;c.querySelector(".ad").onclick=()=>open(v);grid.appendChild(c)})}
function open(v){selected=v;ads=0;loading=false;title.textContent=v.title||"Video";preview.src=v.thumbnail_url||"";text.textContent="Watch 3 ads to unlock this video.";modal.classList.remove("hidden");videoBtn.classList.add("hidden");update()}
function update(){adBtn.textContent=`Watch Ads (${ads}/${REQUIRED})`;bar.style.width=`${Math.min(100,ads/REQUIRED*100)}%`;if(ads>=REQUIRED){adBtn.disabled=true;adBtn.textContent="✓ Ads Completed";videoBtn.classList.remove("hidden");text.textContent="Video unlocked. Tap Watch Video."}else{adBtn.disabled=false;videoBtn.classList.add("hidden")}}
async function showAd(){if(loading||ads>=REQUIRED)return;loading=true;adBtn.disabled=true;adBtn.textContent="Loading Ad...";try{if(typeof window.show_11571866!=="function")throw Error("Monetag SDK not loaded");await window.show_11571866();ads++;update()}catch(e){console.error(e);text.textContent="Ad is not available right now. Please try again.";adBtn.disabled=false;adBtn.textContent=`Watch Ads (${ads}/${REQUIRED})`}finally{loading=false}}
function go(){if(!selected||ads<REQUIRED)return;if(!selected.video_url){text.textContent="এই পোস্টের video_url Supabase-এ দেওয়া নেই।";return}const q=new URLSearchParams({title:selected.title||"Video",thumb:selected.thumbnail_url||"",video:selected.video_url});location.href=`video.html?${q}`}
adBtn.onclick=showAd;videoBtn.onclick=go;document.getElementById("closeModal").onclick=()=>modal.classList.add("hidden");modal.onclick=e=>{if(e.target===modal)modal.classList.add("hidden")};document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");category=b.dataset.category;render()});load();
